### ISSUE TITLE
Game crash when enable trajectory

### ISSUE THREAD

**Issue by dark-tet** [segovo/TrajectoryFabric#6]
![image](https://user-images.githubusercontent.com/32560705/90912870-2a0dcd00-e3fd-11ea-980d-0546b71cb397.png)
'---- Minecraft Crash Report ----
// Shall we play a game?

Time: 8/21/20, 10:22 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at net.Segovo.TrajectoryFabric.TrajectoryFabric.getConfigColor(TrajectoryFabric.java:94)
	at net.Segovo.TrajectoryFabric.TrajectoryFabric.lambda$onInitializeClient$0(TrajectoryFabric.java:255)
	at me.shedaniel.cloth.api.client.events.v0.ClothClientHooks.lambda$null$36(ClothClientHooks.java:199)
	at net.minecraft.class_761.handler$zoe000$renderCenter(class_761.java:7129)
	at net.minecraft.class_761.method_22710(class_761.java:1340)
	at net.minecraft.class_757.method_3188(class_757.java:727)
	at net.minecraft.class_757.method_3192(class_757.java:546)
	at net.minecraft.class_310.method_1523(class_310.java:1023)
	at net.minecraft.class_310.method_1514(class_310.java:656)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
'

**Comment by venashial** [comment]
My game crashed with a bunch of OpenGL errors with the 1.0.10 version, but the version you linked above worked without crashing.

**Comment by segovo** [comment]
Good, the 1.0.11 version checks and fixes the config. I must've made a mistake with a previous version of the mod somehow leading to config's getting messed up.

Official release 1.0.12 on curseforge includes this fix.
